---
########################################################################################
#
# Pass vars_files filename from the command line:
#
#    Example: 
#
#             ansible-playbook pb_ots_cluster.yml -e "id=2node"
#
########################################################################################

- name: C R E A T E  O N T A P  S E L E C T  C L U S T E R

  hosts: "localhost"
  gather_facts: false

  vars_files:
  - vars_ots_cluster_create_pwd.yml
  - "vars_ots_cluster_create_{{ id }}.yml"

########################################################################################
# TASKS
########################################################################################

  tasks:
 
  - include_role:
      name: ots_cluster_create

########################################################################################
# END PLAYBOOK
########################################################################################
